### Save watcher
POST http://localhost:8082/public/api/v1/watcher
Authorization: Bearer <access-token>
Content-Type: application/json

{
  "date": "2022-10-22",
  "projectId": "6359c20fea6757775ceca286",
  "minutesAmount": "360",
  "comment": "Сделала авторизацию"
}