### Sign up person
POST http://localhost:8082/public/api/v1/watcher
Authorization: Bearer <access_token>
Content-Type: application/json

{
  "id": "6359d0baf1339ed8b904fb00",
  "date": "2022-10-22",
  "projectId": "6359c20fea6757775ceca286",
  "minutesAmount": "360",
  "comment": "Сделала авторизацию"
}

### Get watcher
GET http://localhost:8082/public/api/v1/watcher/6359d0baf1339ed8b904fb00
Authorization: Bearer <access_token>
Content-Type: application/json

### Get watcher by user id and date
GET http://localhost:8082/public/api/v1/watcher/all-own-between-dates?from=2022-10-24&to=2022-10-25
#Authorization: Bearer <access_token>
Content-Type: application/json

### Get all watcher
GET http://localhost:8082/public/api/v1/watcher/all?page=0
Authorization: Bearer <access_token>
Content-Type: application/json