spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGODB_URI:}
  main:
    banner-mode: off

mongock:
  enabled: true
  transaction-enabled: false
  default-migration-author: mongock
  migration-scan-package:
    - com.nosql.authservice.configuration.mongodb.migration
