spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:}
      password: ${MONGODB_PASSWORD:}
      database: ${MONGODB_DATABASE:}
      authentication-database: admin
  main:
    banner-mode: off

app:
  password-hashing-secret-key: ${PASSWORD_HASHING_SECRET_KEY:}
  cors-allowed-origin: ${CORS_ALLOWED_ORIGIN:}

mongock:
  enabled: true
  transaction-enabled: false
  default-migration-author: mongock
  migration-scan-package:
    - com.nosql.authservice.configuration.mongodb.migration

jwt:
  issuer: ${JWT_ISSUER:nosql-it-company}
  access-token:
    ttl: ${JWT_ACCESS_TOKEN_TTL:PT30M}
    keystore:
      password: ${JWKS_ACCESS_TOKEN_PASSWORD:}
      resource-path: ${JWKS_ACCESS_TOKEN_RESOURCE_PATH:jwks/nosql-access-token.jks}
      keypair-alias: ${JWKS_ACCESS_TOKEN_KEYPAIR_ALIAS:nosql-access-token}
  refresh-token:
    ttl: ${JWT_REFRESH_TOKEN_TTL:P180D}
    keystore:
      password: ${JWKS_REFRESH_TOKEN_PASSWORD:}
      resource-path: ${JWKS_REFRESH_TOKEN_RESOURCE_PATH:jwks/nosql-refresh-token.jks}
      keypair-alias: ${JWKS_REFRESH_TOKEN_KEYPAIR_ALIAS:nosql-refresh-token}
