spring:
  application:
    name: document-service
  data:
    mongodb:
      uri: ${MONGODB_URI:}
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:nosql-it-company}
          jwk-set-uri: ${JWKS_URI:}

mongock:
  enabled: true
  transaction-enabled: false
  default-migration-author: mongock
  migration-scan-package:
    - com.nosql.document.configuration.mongodb.migration
