server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/it-service-db?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/public/api/v1/auth/.well-known/jwks.json


