server:
  port: 8083

spring:
  data:
    mongodb:
      username: mongo
      password: mongo
      database: it-service-db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/public/api/v1/auth/.well-known/jwks.json

app:
  cors-allowed-origin: http://localhost:3000
