version: '3.9'

x-mongodb-variables: &default-mongodb-authentication
  MONGODB_HOST: mongodb
  MONGODB_PORT: 27017
  MONGODB_USERNAME: mongo
  MONGODB_PASSWORD: mongo
  MONGODB_DATABASE: it-service-db

x-auth-variables: &default-auth-jwks
  JWKS_URI: http://auth-service:8080/public/api/v1/auth/.well-known/jwks.json

x-cors-variables: &default-cors
  CORS_ALLOWED_ORIGIN: http://localhost:3000

services:
  mongodb:
    image: mongo:5.0.12
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  auth-service:
    image: backend/auth-service
    build:
      context: ../backend/auth-service
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      <<: *default-mongodb-authentication
      <<: *default-cors
      PASSWORD_HASHING_SECRET_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDuF9h6lPBF9F9A2eWRMQkYHrvCm2TXz/6QuCxmHZZGgSsvFM8C/KqAq+4n/zrCNlgV1FLcWFInHEmtmgVbfAtkCarFOU7kBTYDhLgVGJUdX5kYVPIA7VdC9Yj3mBnDe2nr8TmTGZipkJcAaf/8a6B9Et1VTPQr4dqO+7RsiiT5oeQlwbkntXbREooTX9xy/GxUURuNMUF13Nc5tILx6ttp85DiDv4viUcowZcEhMLG1PabJYISQsUhyrsGSdU/zkul4RHv9dS9AFYrTZTt3eWD0vODgjp6H6iT5iDqPuJGjmNQLPQ7unFWhMSuoyVn6KQp6/lZgaMLrHJ9MYVjfwnNAgMBAAECggEAREGJyfqQtz1LYWgWK/2GwedtpGiwDD6QmCR0dgHdZvD41FJ+1jhhGOoxKD4/NhYmQnvQFWMsihHN/Xq+Nm/lRBSRZGD9gNkNlwyhSUr21KjnVtZjWmiwL338eh6cpDHpN7675rPb1CCjaXb57/9azwBte1rIVRw2b+8w1jz0RKva+6P98tFwOzVxVpramPwjLo6WKSs+u4x0QC+S5Np986hRcy0NqO8N0JiWSgBB88vfRBKdOdVzAYZgBtpCoc0DnAd0A5+0x/eCb44yAW+Mqie3zaJgcmssNVoH3JnXN3XWB9S63cXX6i5H6iirP4eDjiiDM78ygCGJYsFCY4a3gQKBgQD/uHAZ2hOiVyA2Pzg2UxsY48xCNOQ0gSjjB3d8bOa83xY1Egx6DCeq/l7xtDHRf9ALTg7dx3/FzNlgVCGQuOJaRjOhFBXqHkp+Xaj5F4jLQNnuTTo8tZYzUnKTEtmZQiRfUHTWJw7LqjWZzqo8b7J6N2YHLmBupQql1HlSe3IsFQKBgQDuWnmNHZGn1GYHlByDkmhvsJcZAfMDYTqwDxYfeeDtPhf9F+tlQzOEhB5sYKPhQLn9j3KEEyHgHZqCk0cKpOcukPX7zJ4gQVfK9A8WCacnwU4gjdZu9Zg/PHYLb0WfHTLWoTplqdXPNDWhr2b8loE6DrNGGXAmE2fXnDPLuMf82QKBgQCE+0QInZiyRn6w1yWDUqp3wha5o0m9aCF8FqjzYqqHM7gXtyAX4/RI/uke5qc1nDLzfg9LE/EFSucMKhQeb5b+fR1iOdC/pCr3FfvGNY/kqv/p5e1QHtpSLCD7DMVt5rCFhJCNwVf3X7dqGcf7j9aPqfl76IkrYNZtsFW7KAkSlQKBgQDHh3mlhhE+m3Fl+rj78331sbBrQNR8CdKlO5vbcZ23PHm8Z1+o/16LGkaVlzjZAeQwvPqyUYnUITQNBtk7sdvNgZBJ33qnqcuinDhczGvfvdR3MAVIEdQHa8etvtJbZof+YC2QmWHg+OXEmh7uZ9d6EIBGuFjHpwsQ1TQO4HqZ0QKBgBIaHHnje6F3+ZcZtaZze7FtCpchIoCkYttNnZPtJjb3y6zOrIOyBBTTuG8q8ML/NmpLqF93DAOP9aI3UxIZhPksEV8cSVkB2DEZZ9SIt3/Pb+kmspKQ5ilCqWoiziGbZg8Cx1/gvaWjH393hNiiGYjNHncm1c1KFr7ZZv6rwUOj
      JWKS_ACCESS_TOKEN_PASSWORD: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCrfh23TYeMuk/jGD4VUNzYV5OXvRf9CnOUT7mqe9IdsdC0HZxKwAqEnG+prhQet7+9KUpPYn7C17YiUIlyJNyST1l8scNqrih6x3ryM7u8wzTJromtLxiwokPPKyL8Ggo+v0PYLtBqF8Jvy8oVZ18+c/hG2VMGucsu7iBSxgCOnaL0GfFYN30H1oIEyR2gG2BvniHLoNzHD1/bNTLwLllRPbz4xUnZCbitKX4MhbcV+gi6LqdQp8Rb/FrDuNcODoaauQSdckAx0Px8dHPWBQutISp0fcurxm2pfqxu993Q7MgQVyie3Z3gP2uLC8r5w2gjovZRvV467r1SXEgOWYfzAgMBAAECggEAPebAAzJRA1MdEvPlNPyDOvQhqlvvFL95CMfeVNNs/Jr6ooktqS24njV5eN4FFTFuXHFTCWScLOiALdK0SidUFtvdiU0BJLjIk8j9b/+MfI5Zt5Lwzzp4xwlLQLRpZGZh3FRdwOLlB+aboI8G2sL9diWWMLyxY3QdC0uZD0e5W8Cjkcc4Jh9zwzvR86VjF0z9JoEGy7r+XGnkYWO0Q51uy4QyuIPlUA99LGm2cPwzkAJO9+zAHpqsGJanfOuaH72b4plxwLqw4Kryxok9S60SBTYJQPqcIYgwTYx4y8/2RaA9ZYn1xtzXwOi8+QCwk2PWuKqeNE//99dwbX7VMmzrAQKBgQDUlRUPhfF4CHvOfQPtd2m3x9fXu2spDEcZMdyKEkgnUzYIQRcKoj4Kf/5dDKB6mBLtiYLDXRPV127EVOeCAaWAuNzgGPw08j1q7L+qYFfJSLnAbYzd89Ai5sTbCjsKDY+0fEVzb1+9tYPobq44remg7W/fNB3onfW/EJJ2QyzicQKBgQDOhKYP/oRrTJVBhJL9HbK8cWz5Uxy+/Z1pxm8xv35HtlByhhat0Cc4Ii+DZ8GEvFiHjpByKBkj5hesNf3XesuXf3Q02z85naQnUZbKcgPbxuzBTfoM1ysrRak2rqnudEA27LpnsVMfeh2fqVVqmeSTvOUDNxhbeC9b4HynGVP6owKBgQCetS6kCDvegXbtEih8gUpMCsb6KNI4MxJhnPgpnLyBn34Xa4DoT3hCHoyoq2SkIiT/ckpN0I+edtgbe8fbJ5+IGnvMUtr4LGHuEhKGAKeJfuIu55rjmcMqS19sqJarSrSe6qhvJhc0au+v9/HaHvztSFbdLOunX0a4/oZaBIzeAQKBgHFaldvJk91hV7tyjUupdWXBzFK9r9WVV0WryXTA6wtpopZ5yxD0Y9KH0RSLasj0qJMfSWGfaM0vimbX69DOcdlh9+LbRMTXJjb+rYnJMxz6/xDLQCi0IdnKjqqZDGT6IhUDsv0fc8SfPotYYq30cmY1FG7DWvc57KS9fy4o1NOJAoGBALRexEU9U3pG6+2ZOW+LzVDdRZA4Gln/vOoZn0EOEJiA6gqWvfCjHnml0+/Tzl6jwdu12Tm27GA4Ko2ri9HrFkP8sGWuPSgeCN+Q4t+Wf/4yc7xFVUUbkj92diEFFpoeYnP9+HP7tBsy0nKtxNrRVFZi/gk8d64DxokwjcnsLoCN
      JWKS_REFRESH_TOKEN_PASSWORD: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCm8o4tAJzyrbPDilpxLJppTb9oRwzV8ZJf2OH5TPFEbl/CN/DBDJnvK4XWa7TZJK55RqcZh0IuaiVqDI5LaXOsX5utac8xpWNO88YJVaydyNBt5l4wAWBrxheuSQHaTGAtapp/kf5mdcCqPwWTA+wWC/VJBxMAlEOjMlc/gcVw42cHcgG1JNaQOSm/0GAMFlFQlTq47zpQAVViwRNNnINsP8S/N6ncSpJna2rmXZlALsnYdman92M5VX8eq1//B+KJ+CURkuHFFGaGCy1VNF1wycB3FIFg9nIT2TiGjPDC/nrB4n8e/4U+vF3rNQYYooCLODxAn4K5T//eqEIbZyclAgMBAAECggEAXbU0XMpFTmp1xsJ39aKloYoEcFHBQK1yDd69KKQpoNGbanbf6lxaY0c4vpyCTIgsbuJblRa47Tije51Emcu9I/oedf44UJOW5JAsjrzKQV6gr69pGuUK7DOqwyczpQbNzXBS/FxEQdrCpEzvog/HirB3o+AWqHKQbKArHPiIjM4PvIryZ7a1A7fDrYWIZ3pzf4CtTXSo7fyBETeFpSnYunQEn4WKKn13//wsNeayPvnRxFic29Smg/iZR+3Md/XG5EkitkxqZJQ8qyqv+E4aPaKTKKGyeUApfn1B3oF5m7gx/rio3z0NTgmQbtWFxFYZrUFk8aiiG4YM7RoKbSBXWQKBgQDSwkycgAEsWMeAF7dJefllVsVGK+9yliNdVw8Q55G6+n1KI6hXk/5b5sWgK6qpnyVFEp4yCR72hexluC0NKn9MHEEkrAhdo3GTekyVT9ITTfyYcWiTYs+UVweVolygDsPeXpElbTyNGKjvE1AWaTLyaiELqV3UgOQ37tTa/lioiwKBgQDKyLYck7wJrfQGrYgZ8iTAQjbco129fddZst1KFlJIQR+yTFJVW7BBJ2NbuuM0LdzLOe9NNgsyQN5ofp7OYo331CPENCo12QUJlQL7CwjG5tl0Yjj7/O++jlOPvcrnyw5volXgbLMHb/nq2luu8Cu+tXBOuwsmbpcQXB4epYG1DwKBgGoe6YJ3tZ+FyFZIGsMFhr0vFsABiVzSGlZ6apyhbTCPxhxZnf8TBqVxqpq+wf0MpDCGcl9RVmTdBC4nsY+KkXRaWbbEZKX5kUun7f3UpjuQLhr4J6bmvwy7UZdXnHn/VUKXrVACE9Ybz5wpxk6yg7OqGp+LlTJWABPlzwnBvhSHAoGBAJs5JF2foJJwO5lZABOMTSF2DfS6gKjqSQv6ZHWvvHBemVqsHWIFe1eERQQUfJKWgKp3wHwD4HIpQZYPRpSI0E9ibbZkj+MEKlz5WXy9J4zJbK8v+Jq7NPFSlRg0mbrwri45vy65RhltV4q0dvXkFjg3Pq6lcpWKlcwKF2wyGKV1AoGAHjaCk/+yzFkaNTGtIuijXKIk2vZfhVIH4dxhLfNV6Q5dfsuknb3mKQPv0wyutQxWki9mVCkht3UeQOI35Kn5C2GobIW82mtuZ7pBAuBuwAe/62VovTxK/AeIu/u73YxOcdsORC0TPbgax4XodnESPogrB6D9T55u3bM04QPMlL4=

  person-service:
    image: backend/person-service
    build:
      context: ../backend/person-service
    depends_on:
      - mongodb
      - auth-service
    ports:
      - "8081:8080"
    environment:
      <<: *default-mongodb-authentication
      <<: *default-auth-jwks
      <<: *default-cors

  watcher-service:
    image: backend/watcher-service
    build:
      context: ../backend/watcher-service
    depends_on:
      - mongodb
      - auth-service
    ports:
      - "8082:8080"
    environment:
      <<: *default-mongodb-authentication
      <<: *default-auth-jwks
      <<: *default-cors

  document-service:
    image: backend/document-service
    build:
      context: ../backend/document-service
    depends_on:
      - mongodb
      - auth-service
    ports:
      - "8083:8080"
    environment:
      <<: *default-mongodb-authentication
      <<: *default-auth-jwks
      <<: *default-cors

volumes:
  mongodb-data:
