### Sign up user
POST http://localhost:8080/public/api/v1/auth/sign-up
Content-Type: application/json

{
  "login": "new-user",
  "password": "a4f3"
}

### Sign in user
POST http://localhost:8080/public/api/v1/auth/sign-in
Content-Type: application/json

{
  "login": "new-user",
  "password": "a4f3"
}
