### Sign up user
POST http://localhost:8080/admin/api/v1/auth/sign-up
Authorization: Bearer <access_token>
Content-Type: application/json

{
  "login": "new-use",
  "password": "a4f3",
  "role": "HR"
}

### Sign in user
POST http://localhost:8080/public/api/v1/auth/sign-in
Content-Type: application/json

{
  "login": "hr",
  "password": "hr"
}
