### Sign up user
POST http://localhost:8080/admin/api/v1/auth/sign-up
Authorization: Bearer eyJraWQiOiIxMDg1NzAyNzQ2NjMwMTQ3NzUyMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJub3NxbC1pdC1jb21wYW55Iiwic3ViIjoiNjM4YjllMjFmZTljZmEzNGQ5M2JlOTNkIiwiaWF0IjoxNjcwMjUxNzcwLCJleHAiOjE2NzAyNTM1NzAsInJvbGUiOiJIUiJ9.YLYysDJi1hTBJOBOChVS9IJyr-npYe0UeQlUaEsdaL5w5qrdGGKFkJuT1ylzxxqmGpbkg-nB1ce2OAlPkVTAY4TGkT1WfhgkOxkkwHMZBTjm79AFVc3Kla2w6pjF7PQluEnZQXk4DxweWwYdHnhQa8aaVM3DrJ8L7BeSyw22f4G0iXQv0_TnYrRY_W_nkjQbjsv_6bTqKsgHJjVwHxCB0T4RylvU5MxHPzEH2KqWf-bDoZGXKUf7wd34nmbX5r7cTAg0JygC9CWISLGTBLYjc4clDI6TD8jIQLAjsME7jZC_4Y7Gu7y1lZwH4EBgPSvgPWwxTPtaUramZtwH4x6Guw
Content-Type: application/json

{
  "login": "new-use",
  "password": "a4f3",
  "role": "HR"
}

### Sign in user
POST http://localhost:8080/public/api/v1/auth/sign-in
Content-Type: application/json

{
  "login": "hr",
  "password": "hr"
}
