### Sign up person
POST http://localhost:8081/admin/api/v1/person/sign-up
Authorization: Bearer eyJraWQiOiIxMDg1NzAyNzQ2NjMwMTQ3NzUyMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJub3NxbC1pdC1jb21wYW55Iiwic3ViIjoiNjM4YjllMjFmZTljZmEzNGQ5M2JlOTNkIiwiaWF0IjoxNjcwMTA5Njg4LCJleHAiOjE2NzAxMTE0ODgsInJvbGUiOiJIUiJ9.aGxE0-pVWtuMIzow7vYRCNdb1f37Iu9SheYgvM0A9a4lKJyVI61T8Hs1FalDdCpGrK40bUsEBWN6nLJL5MLSodQI6ilaLrsIm1pqI3t-6gEXNZG-KtOLsWcMJ8ggn5JVZqDQNonbFJP-T1X0xzKtls5D4BqEscHSXrl8KIg3dR5h9a9Z9Z_XfzJE93gj0z8o7jIE4Jj7lI9p4i6vEtCo2pQGLlJzHrc0xdbnTK6BPAPBTM6kw7CeTWsdVi4kNXha5cLBn4pFN8wkGjXewY7MiyPNq7j8-wcnxkc-eww_L61rvHuw3uib7y4KqxiqtKEE0PngDSwt1yMqpQdryWJHpA
Content-Type: application/json

{
  "id": "638b9e21fe9cfa34d93be93d",
  "name": "Екатерина",
  "surname": "Аксёнова",
  "patronymic": "Александровна",
  "age": "25",
  "sex": "FEMALE",
  "birthday": "2001-11-14",
  "firstWorkDate": "2022-04-14",
  "position": "JUNIOR_BACKEND_DEVELOPER",
  "status": "WORKING",
  "contacts": {
    "phoneNumber": "79112886438",
    "email": "kate.kate6575@gmail.com"
  },
  "jobTime": {
    "start": "11:00",
    "end": "20:00"
  },
  "officeId": "6359c11c2416d454722f826f",
  "confidential": {
    "passportData": {
      "number": "BM5653789",
      "issuedPlace": "Октябрьский РОВД",
      "issuedDate": "2015-10-14"
    },
    "nationality": "BELARUS",
    "address": "Улица Торжковская, дом 15",
    "salary": "1000000",
    "projectIds": [
      "6359c20fea6757775ceca286"
    ]
  },
  "comment": "Устала"
}

### Edit person
PUT http://localhost:8081/admin/api/v1/person/63851fa5b7f3da0911b81ed5
Authorization: Bearer <access_token>
Content-Type: application/json

{
  "id": "63851fa5b7f3da0911b81ed5",
  "name": "Katykha",
  "surname": "Аксёнова",
  "patronymic": "Александровна",
  "age": "25",
  "sex": "FEMALE",
  "birthday": "2001-11-14",
  "firstWorkDate": "2022-04-14",
  "position": "JUNIOR_BACKEND_DEVELOPER",
  "status": "WORKING",
  "contacts": {
    "phoneNumber": "79112886438",
    "email": "kate.kate6575@gmail.com"
  },
  "jobTime": {
    "start": "11:00",
    "end": "20:00"
  },
  "officeId": "6359c11c2416d454722f826f",
  "confidential": {
    "passportData": {
      "number": "BM5653789",
      "issuedPlace": "Октябрьский РОВД",
      "issuedDate": "2015-10-14"
    },
    "nationality": "BELARUS",
    "address": "Улица Торжковская, дом 15",
    "salary": "1000000",
    "projectIds": [
      "6359c20fea6757775ceca286"
    ]
  },
  "comment": "Устала"
}

### Delete person
DELETE http://localhost:8081/admin/api/v1/person/6359c5e317df7f8644c2cea2
Authorization: Bearer <access_token>
Content-Type: application/json

### Update person's contacts
PUT http://localhost:8081/public/api/v1/person/contacts
Authorization: Bearer <access_token>
Content-Type: application/json

{
  "phoneNumber": "375297169253",
  "email": "kate6575@gmail.com"
}

### Get person
GET http://localhost:8081/public/api/v1/person
Authorization: Bearer <access_token>
Content-Type: application/json

### Get person by name
GET http://localhost:8081/public/api/v1/person/name?name=кат
Authorization: Bearer <access_token>
Content-Type: application/json

### Extended get person
GET http://localhost:8081/public/api/v1/person/extended
Authorization: Bearer <access_token>
Content-Type: application/json

### Get all person
GET http://localhost:8081/public/api/v1/person/all?page=0
Authorization: Bearer <access_token>
Content-Type: application/json
